services:
  excalidraw:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: excalidraw
    ports:
      - "3000:3001"
    restart: unless-stopped
    stdin_open: true
    tty: true
    environment:
      - NODE_ENV=development
